name: Build and Push Docker Image

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: simple-port-checker

jobs:
  build:
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      contents: read
      packages: write
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Extract version from pyproject.toml
        id: version
        run: |
          VERSION=$(python -c "import tomllib; print(tomllib.load(open('pyproject.toml', 'rb'))['project']['version'])")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ steps.version.outputs.version }},enable={{is_default_branch}}
          labels: |
            org.opencontainers.image.title=Simple Port Checker
            org.opencontainers.image.description=A comprehensive tool for checking firewall ports and L7 protection services
            org.opencontainers.image.vendor=htunn
            org.opencontainers.image.licenses=MIT
            org.opencontainers.image.version=${{ steps.version.outputs.version }}
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VERSION=${{ steps.version.outputs.version }}

      - name: Test Docker image (local build)
        if: github.event_name == 'pull_request'
        run: |
          # Build image locally for testing
          docker build -t test-image:local .
          docker run --rm test-image:local --help
          docker run --rm test-image:local --version

      - name: Test Docker image (pushed)
        if: github.event_name != 'pull_request'
        run: |
          # Test the pushed image
          docker run --rm ${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:${{ steps.version.outputs.version }} --help
          docker run --rm ${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:${{ steps.version.outputs.version }} --version

  integration-test:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name != 'pull_request'
    
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      
      - name: Extract version from previous job
        id: version
        run: |
          VERSION=$(python -c "import tomllib; import requests; r = requests.get('https://pypi.org/pypi/simple-port-checker/json'); print(r.json()['info']['version'])")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Latest PyPI version: $VERSION"

      - name: Wait for Docker Hub propagation
        run: |
          echo "Waiting for Docker image to be available..."
          sleep 60  # Wait 1 minute for Docker Hub propagation

      - name: Test basic functionality
        run: |
          echo "Testing basic port scan..."
          docker run --rm ${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest scan google.com --ports 443 --timeout 5

      - name: Test L7 protection detection
        run: |
          echo "Testing L7 protection detection..."
          docker run --rm ${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest l7-check google.com --timeout 5

      - name: Test certificate analysis
        run: |
          echo "Testing SSL/TLS certificate analysis..."
          docker run --rm ${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest cert-check google.com --timeout 10
          docker run --rm ${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest cert-info github.com --timeout 10
          docker run --rm ${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest cert-chain cloudflare.com --timeout 10

      - name: Test full scan integration
        run: |
          echo "Testing full scan with all features..."
          docker run --rm ${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest full-scan google.com --ports 443 --timeout 10

      - name: Test mTLS functionality
        run: |
          echo "Testing mTLS check..."
          docker run --rm ${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest mtls-check google.com --timeout 10 || true  # Allow to fail

      - name: Test DNS trace
        run: |
          echo "Testing DNS trace..."
          docker run --rm ${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest dns-trace google.com --timeout 10

      - name: Validate certificate commands exist
        run: |
          echo "Validating certificate commands are available..."
          docker run --rm ${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest --help | grep -E "(cert-check|cert-chain|cert-info)"
          echo "✅ All certificate analysis commands are available"

      - name: Test with specific version tag
        run: |
          echo "Testing with version-specific tag..."
          docker run --rm ${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:${{ steps.version.outputs.version }} scan github.com --ports 443 --timeout 5

  security-scan:
    runs-on: ubuntu-latest
    needs: [build, integration-test]
    if: github.event_name != 'pull_request'
    
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
